jobs:
  odoo:
    machine: true
    steps:
       - checkout

       - run:
          name: Login to Quay.io
          command: docker login quay.io -u "${QUAY_USER}" -p "${QUAY_TOKEN}"

       - run:
          name: Select docker-compose.yml file
          command: echo 'export COMPOSE_FILE=.docker_files/docker-compose.yml' >> $BASH_ENV

       - run:
          name: Build -- Init Odoo
          command: docker-compose run --rm odoo odoo --stop-after-init -i main

       - run:
          name: Setup Log Folder For Reports
          command: sudo mkdir -p .log && sudo chmod 777 .log

       - run:
          name: Run Test
          command: docker-compose run --rm odoo odoo --stop-after-init -u main --log-level test --test-enable

       - store_test_results:
          path: .log

workflows:
  version: 2
  basic-odoo-test:
    jobs:
      - odoo:
          context: quay.io